name: Deploy to reg.ru

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js (if needed for build)
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # Опционально: минификация CSS/JS
    - name: Build and optimize (optional)
      run: |
        # Создать папку dist
        mkdir -p dist
        
        # Копировать все файлы проекта lineflow
        cp *.html dist/ 2>/dev/null || true
        cp *.js dist/ 2>/dev/null || true
        cp -r css dist/ 2>/dev/null || true
        cp -r modules dist/ 2>/dev/null || true
        cp -r js dist/ 2>/dev/null || true
        cp -r assets dist/ 2>/dev/null || true
        
        # Убедиться что основные файлы скопированы
        ls -la dist/
        
        # Список файлов для проверки
        ls -la dist/
    
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/README.md
          **/.DS_Store
    
    - name: Notify deployment
      run: |
        echo "✅ Deployment completed to lineflow.xyz"
        echo "🕒 Deployed at: $(date)"